sips/sip-000-stacks-improvement-proposal-process.md
sips/sip-001-burn-election.md
sips/sip-002-smart-contract-language.md
sips/sip-003-peer-network.md
sips/sip-004-materialized-view.md
sips/sip-005-blocks-and-transactions.md
sips/sip-006-runtime-cost-assessment.md
sips/sip-007-stacking-consensus.md
sips/sip-008-analysis-cost-assessment.md

This PR adds all existing SIPs from https://github.com/blockstack/stacks-blockchain . No modifications have been made.

fix: adds existing SIPs from stacks-blockchain

---

sips/sip-005/sip-005-blocks-and-transactions.md

bugfix: "origin account" --> "each account"

---

sips/sip-007/sip-007-stacking-consensus.md

Originally from: https://github.com/blockstack/stacks-blockchain/pull/2445

Fix misspelled word

---

sips/sip-005/sip-005-blocks-and-transactions.md

- Fix field ID values in spending field body for signatures in SIP-005
- Correct typos and grammar in SIP-005

Fix field ID values in SIP-005

---

sips/sip-007/sip-007-stacking-consensus.md

A super minor typo fix towards the end of SIP-007

Fixes typo: recomments -> recommends

---

sips/sip-003/sip-003-peer-network.md

SIP003: Fix code block

---

considerations/governance.md

This PR adds details for the governance CAB including a list of items in-scope for review.
Closes #26
Please let us know if any additional information is needed!

feat: add governance CAB details

---

considerations/minutes/2021-11-05-governance-cab-minutes-sip-012.md

This PR adds the minutes for the 2021-11-05 Governance CAB meeting regarding [SIP-012](https://github.com/stacksgov/sips/pull/41).

Add Governance CAB minutes for 2021-11-05

---

sips/sip-005/sip-005-blocks-and-transactions.md

fix: add StringASCII and StringUTF8

---

sips/sip-005/sip-005-blocks-and-transactions.md

chore: update SIP-005 content around NFT post condition codes

---

considerations/economics.md

Pieter with his experience in defi from Arkadiko and his computer science background, will be a great member and eyes for the community by joining the Economics CAB.

Adding Pieter from Arkadiko to Economics CAB

---

considerations/minutes/economic-cab/2022-10-29-economic-cab-minutes-sip-15.md
considerations/minutes/economic-cab/template.md

adding minutes for the Economic CAB discussion on SIP-015

Economic CAB minutes for SIP-015

---

considerations/minutes/governance-cab/2022-11-17-sip-015.md

This PR adds the Governance CAB minutes for the decision on SIP-020, with all members in favor :+1:

Add gov cab minutes for sip-020

---

considerations/minutes/technical-cab/2022-11-23-sip-020.md

This PR adds the Technical CAB minutes for the decision on SIP-020, with voting members in favor 👍

Adding tech CAB minutes for sip-020

---

sips/sip-015/sip-015-network-upgrade.md

This was discussed in the comments, and updated in the implementation, but never made it into the actual SIP.

fix: updated `?` suffixes

---

sips/sip-015/sip-015-network-upgrade.md

Is the name just missed? 
If it was approved by all Considerations specified, Economic CAB was one of them, and received signed off from the chairperson @mattyTokenomics ? Unless Matty opted out of putting name down?

Economic chairperson's sign off?

---

considerations/minutes/governance-cab/2023-04-20-sip-022.md

This PR adds the Governance CAB minutes for the decision on SIP-022, with all members in favor :+1:

Add gov cab minutes for SIP-022

---

sips/sip-022/sip-022-emergency-pox-fix.md

Does it make sense for the CAB chairs to open a PR like this upon approval?

Add SIP-022 sign-offs and update status

---

considerations/minutes/governance-cab/2023-05-01-sip-023.md

This PR adds the Governance CAB minutes for the decision on SIP-023 with unanimous approval.

Add gov cab minutes for SIP-023

---

sips/sip-023/sip-023-emergency-fix-traits.md

Adding signoff line to SIP-023

chore add CAB signoff for SIP-023

---

considerations/minutes/governance-cab/2023-05-17-sip-024.md

This PR adds the Governance CAB minutes and decision on SIP-024 (#141),  with 4/5 members voting yes and one abstained.

Add gov cab minutes for SIP-024

---

sips/sip-022/sip-022-emergency-pox-fix.md

Updates SIP-022 to `Accepted` status

SIP-022 sign-off

---

sips/sip-023/sip-023-emergency-fix-traits.md

Retroactively signing off on SIP-023 as SIP Editor

SIP-023 sign-off

---

README.md
sips/sip-022/sip-022-emergency-pox-fix.md
sips/sip-023/sip-023-emergency-fix-traits.md
sips/sip-024/sip-024-least-supertype-fix.md

This is just a chore to ratify the already-deployed SIPs for the emergency fixes described in SIP 022, 023, and 024.  I added the relevant sign-offs.
Will merge later today if there are no objections.

Ratify SIPs 022, 023, 024

---

considerations/minutes/technical-cab/2023-10-27-pr-152-153.md

docs: add meeting minutes for technical CAB

---

sips/sip-021/sip-021-nakamoto.md

@kantai I addressed that paragraph we discussed here, as well as cleaned up some other minor things. I added a TODO to fill in the voting process for non-stackers.
I also have one remaining question about whether cycle 75 is intended to be the number used in the "For Miners" section.

docs: minor updates to improve the SIP

---

considerations/minutes/governance-cab/2024-02-02-sip-021.md

This PR adds the Governance CAB minutes and decision on SIP-021 (https://github.com/stacksgov/sips/pull/155), with 4/5 members voting yes and one abstained.

Add gov cab minutes for SIP-021

---

considerations/technical.md

Updates to contact information in the Technical considerations document and adds a new section to define the process for reaching a decision on SIPs within the CAB.

Define CAB voting process and bring contact information up to date.

---

sips/sip-000/sip-000-stacks-improvement-proposal-process.md

There are wrong words in the content and use this commit to fix them.

chore: fix typos

---

README.md

SIP-025 .md path error correction.

Update README.md - SIP-025 path

---

README.md
considerations/minutes/technical-cab/2024-11-14-sip-aligning-incentives.md

Adds results for the SIP-029 technical cab vote.

Technical CAB Vote on SIP-029

---

considerations/minutes/governance-cab/2024-10-21-sip-028.md

Draft from today's CAB meeting, still a WIP.

Add gov cab minutes for SIP-028

---

README.md

Link not working. 
Path should be: https://github.com/stacksgov/sips/blob/main/sips/sip-028/sip-028-sbtc_peg.md

Update README.md - SIP-028 md path

---

considerations/governance.md

governance: add PeaceLoveMusic.btc

---

sips/sip-031/sip-031.md

These are some minor technical details that should be corrected. These changes have no meaningful effect on the intent of what is written.

SIP-031 tech updates

---

sips/sip-031/sip-031.md

Script file (zip) will be added to the SIP Repo once this has been merged into SIP Repo main.

Update sip-031.md - Adding voting results (Activation Status)
